name: Export game
run-name: Export game

env:
  GODOT_VERSION: 4.1
  EXPORT_NAME: godot-game-template

on:
  push:
    branches:
      - main

jobs:

  # Export game for Linux platforms.
  export-linux:
    name: Linux export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable ~/.local/share/godot/export_templates/$GODOT_VERSION.stable

      - name: Build
        run: |
          mkdir -v -p build
          cp config.cfg scores.txt build
          godot --export-release --headless "Linux/X11" build/$EXPORT_NAME.x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: build

  # Export game for Windows Desktop platforms.
  export-windows:
    name: Windows export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable ~/.local/share/godot/export_templates/$GODOT_VERSION.stable

      - name: Build
        run: |
          mkdir -v -p build
          cp config.cfg scores.txt build
          godot --export-release --headless "Windows Desktop" build/$EXPORT_NAME.x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build

  # Export game for web platforms.
  export-web:
    name: Web export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable ~/.local/share/godot/export_templates/$GODOT_VERSION.stable

      - name: Build
        run: |
          mkdir -v -p build
          cp config.cfg scores.txt build
          godot --export-release --headless "Web" build/index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build
