name: Static code analysis
run-name: Static code analysis

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

env:
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1

jobs:

  # Run static code analysis using gdtoolkit.
  static-code-analysis:
    name: Static code analysis
    runs-on: ubuntu-22.04
    if: github.event.pull_request.draft == false
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install and cache Python test requirements
        uses: ./.github/actions/python_cache

      - name: Execute gdformat
        run: gdformat --diff .

      - name: Execute gdlint
        run: gdlint --verbose .

      - name: Execute gdparse
        run: gdparse $(find . -name "*.gd")
